name: calculadora
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  auto_size_text: ^2.1.0
  font_awesome_flutter: ^8.7.0
  link: ^1.0.0
  cupertino_icons: ^0.1.2

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/launcher/icon.png"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.3

flutter:
  uses-material-design: true
  fonts:
    - family: Quicksand
      fonts:
        - asset: fonts/Quicksand-Regular.ttf
        - asset: fonts/Quicksand-Bold.ttf
        - asset: fonts/Quicksand-Light.ttf
        - asset: fonts/Quicksand-Medium.ttf
        - asset: fonts/Quicksand-SemiBold.ttf
    - family: Karla
      fonts:
        - asset: fonts/Karla-Bold.ttf
        - asset: fonts/Karla-BoldItalic.ttf
        - asset: fonts/Karla-Italic.ttf
        - asset: fonts/Karla-Regular.ttf